### ISSUE TITLE
The plugin seems to ignore config to HTML file

### ISSUE THREAD

**Issue by rfieve** [wallabyjs/jsdom-quokka-plugin#1]
Plugin version : 1.0.5
IDE : Webstorm

The plugin seems to only accept inline-passed html like follows:
```
({
    'plugins' : ['jsdom-quokka-plugin'],
    'jsdom' : {
        'html' : '<h1>test</h1>'
    }
})
```

And seems to refuse to load external HTML file specified in the config like so:
```
({
    'plugins' : ['jsdom-quokka-plugin'],
    'jsdom' : {
        'config' : {
            'file' : 'test.html'
        }
    }
})
```

Wouldn't be a good idea to pass everything in the config object like jsdom accepts (even for HTML fragment)?

**Comment by ArtemGovorov** [comment]
The plugin is [very simple](https://github.com/wallabyjs/jsdom-quokka-plugin/blob/master/index.js), and as you can see, it does pass everything in the config object to jsdom. However, it uses the `jsdom.jsdom(...)` API (not `jsdom.env`), and the API simply ignores the `config.file` setting. 

I think we could extend the plugin to read the file if the `jsdom.config.file` was passed and pass the HTML from the file as html here: https://github.com/wallabyjs/jsdom-quokka-plugin/blob/master/index.js#L5. It shouldn't be too hard to implement - you are welcome to send a pull request if you want the feature ASAP.

**Comment by rfieve** [comment]
Thank you for your quick answer!
I will closely review the jsdom documentation and send you a pull request with this added feature.
It seems indeed really trivial and I believe it would add more flexibility to this great plugin.

**Comment by rsurjano** [comment]
@rfieve did you send the PR you mentioned?

**Comment by rfieve** [comment]
Hello @rsurjano,
Yes it is merged, on master and the moment.
Do you still have issues?

**Comment by ArtemGovorov** [comment]
@IvanMiIosevic The docs were a bit wrong, it's supposed to be like in the initial issue post (`jsdom.config.file`):

```js
({
    'plugins' : ['jsdom-quokka-plugin'],
    'jsdom' : {
        'config' : {
            'file' : './index.html'
        }
    }
})
```

We have also added the `jsdom.file` to mirror the setting. So you may either change your config to use  the `jsdom.config.file`, or update your `jsdom-quokka-plugin` (in your `~/.quokka/node_modules` folder or in your project folder if you've installed it locally) to the latest version and then your current config will work as well.
