### ISSUE TITLE
I can not replicate the example ... 

### ISSUE THREAD

**Issue by Luxcium** [wallabyjs/jsdom-quokka-plugin#12]
<img width="866" alt="Capture d’écran, le 2019-07-26 à 03 03 15" src="https://user-images.githubusercontent.com/42672814/61932702-0c4c0b00-af52-11e9-90ed-5ed52d63e4d8.png">

**Comment by ArtemGovorov** [comment]
In our example the Quokka inline config:

```
({
    plugins: ['jsdom-quokka-plugin'],
    jsdom: {html: `<div id="test">Hello</div>`}
})
```

is the first thing in the file. In your case you have some format/linter comments, that is why it doesn't work. If you remove your comments, it'll work. Alternatively, you may move inline Quokka config to another source of Quokka configuration, such as [`.quokka` file or `package.json` `quokka` section](https://quokkajs.com/docs/configuration.html#quokka-file-config).

**Comment by Luxcium** [comment]
<img width="718" alt="Capture d’écran, le 2019-07-26 à 03 22 59" src="https://user-images.githubusercontent.com/42672814/61933786-b0cf4c80-af54-11e9-8b99-b78e6fec05c1.png">
