### ISSUE TITLE
how to config in IDEA 2020.2?

### ISSUE THREAD

**Issue by heicks** [wallabyjs/jsdom-quokka-plugin#14]
![image](https://user-images.githubusercontent.com/12287943/94222655-8eeaa480-ff20-11ea-9ea0-9ec8cf183141.png)

in doc helper , im not find about **IDEA** any cfg like [ "plugin':"xxxxbabbaba" ]

**Comment by smcenlly** [comment]
It looks like you are trying to run some code that uses jquery. In order to use jquery in your file, you will need to first import it.

Something like:

```javascript
const $ = require('./scripts/jquery-3.2.1.min.js');

$(function() {
...
});
```

> in doc helper , im not find about IDEA any cfg like [ "plugin':"xxxxbabbaba" ]

I'm not quite sure what you mean. Are you able to provide a little more detail and a full code snippet or repo with your issue?

**Comment by heicks** [comment]
im find querstion at web, search it in https://github.com/wallabyjs/quokka/issues/64 , 
![image](https://user-images.githubusercontent.com/12287943/94241052-b6546800-ff46-11ea-96dc-f6deaa06e440.png)

after
![image](https://user-images.githubusercontent.com/12287943/94241146-dbe17180-ff46-11ea-89bf-2dc87515de46.png)

, now this my problem
> Cannot find module 'jquery-1.11.0.min.js'
> Require stack:
![image](https://user-images.githubusercontent.com/12287943/94241684-86f22b00-ff47-11ea-9315-3d70fd6b2141.png)

same as other js libary, :(
![image](https://user-images.githubusercontent.com/12287943/94242009-041da000-ff48-11ea-9d9d-cfc5632eabf3.png)

that page install plugin can use DOM parse
![image](https://user-images.githubusercontent.com/12287943/94242161-33cca800-ff48-11ea-8615-a2f30256e8d8.png)

im here not find cfg in IDEA , that cfg like vs code setting cfg?

**Comment by ArtemGovorov** [comment]
> Cannot find module 'jquery-1.11.0.min.js'

Quokka runs your code in node.js, so any module that you require/import needs to be installed in your node_modules folder. However it looks like the file you are importing  (`jquery-1.11.0.min.js`) is not installed as a node module, so you need to import it as a file, not as a module:

```
const $ = require('./jquery-1.11.0.min.js');
```

> im here not find cfg in IDEA , that cfg like vs code setting cfg?

Quokka doesn't have any IDEA config, all of Quokka config options/sources are described at https://quokkajs.com/docs/configuration.html.
