### ISSUE TITLE
quokka jsdom error

### ISSUE THREAD

**Issue by COD3BREAK3R** [wallabyjs/jsdom-quokka-plugin#15]
I have this error:

```
Cannot find module 'jsdom' 
Require stack: 
- .\index.js 

```

I run the command npm install -g jsdom, then I went to the .quokka folder and in config.json I have the following:

```
{
     "pro": false,
        
     "plugins": ["jsdom-quokka-plugin"]
    
}
```

I do not understand what I have wrong

**Comment by smcenlly** [comment]
Please note that the plugin needs to be installed in either your [Quokka config folder](https://quokkajs.com/docs/configuration.html#global-config-file) or else your local project. If jsdom is only installed as a global dependency (e.g. using `npm install -g`) then Quokka will not be able to find/use it.

**Comment by Dwerg01** [comment]
Thank you @smcenlly, installed jsdom >> stopped and started Quokka extension and now it works.

**Comment by JJ-Dynamite** [comment]
`npm i -g jsdom-quokka-plugin`

**Comment by cdsantiago** [comment]
So how do you fix this ? I don't understand how to install it in the quokka config folder

**Comment by ArtemGovorov** [comment]
@cdsantiago 

```
cd ~/.quokka/
npm i jsdom-quokka-plugin jsdom
```

**Comment by Aladdin1978** [comment]
> @cdsantiago
> 
> ```
> cd ~/.quokka/
> npm i jsdom-quokka-plugin jsdom
> ```

Thanks, that worked for me. Was wondering whether to use the -g flag?

**Comment by smcenlly** [comment]
> Thanks, that worked for me. Was wondering whether to use the -g flag?

No, the `-g` flag is not valid in this case. By installing to `~/.quokka/`, JSDOM will be installed to `~/.quokka/node_modules/jsdom`, which is where Quokka looks for it. If you install with `-g`, Quokka will not find JSDOM.

**Comment by monirulislamkhan** [comment]
> @cdsantiago
> 
> ```
> cd ~/.quokka/
> npm i jsdom-quokka-plugin jsdom
> ```

Thanks, that worked.
