### ISSUE TITLE
jsdom not showing any values

### ISSUE THREAD

**Issue by kinglycodes** [wallabyjs/jsdom-quokka-plugin#16]
Hi, 
I have a quick question about how jsdom works.

**Example:**
```
document.getElementById ('book-form'). addEventListener ('submit', function (e) {
const title = document.getElementById ('title'). value,
author = document.getElementById ('author'). value,
isbn = document.getElementById ('isbn'). value;

console.log (title, author, isbn);

e.preventDefault ();
});
```

Why can't I see the values from the console.log statement in vscode with quokka?
In the browser console in Chrome, the values of title, author and isbn are displayed as soon as I click the button.

P.S. I know it's not the shortest and best spelling, but I need the example for training purposes.
I have the pro version of quokka.

Thanks a lot

Best
Stefan

**Comment by ArtemGovorov** [comment]
Quokka simply runs your code, so to get your event handler triggered you need to programatically click the button (similar to how you manually click it in your browser).

So maybe something like this should do it:

```diff
document.getElementById ('book-form'). addEventListener ('submit', function (e) {
const title = document.getElementById ('title'). value,
author = document.getElementById ('author'). value,
isbn = document.getElementById ('isbn'). value;

console.log (title, author, isbn);

e.preventDefault ();
});

+document.getElementById('book-form').submit();

```

**Comment by kinglycodes** [comment]
Thanks Artem, it works. 👍

**Comment by kinglycodes** [comment]
Hey Artem, 

I was probably too hasty. It doesn't work.

Now I have tested it in an other project. The id of the form is 'form'.

With the following line I get 'NaN' when I select the line
`+document.getElementById('form').submit();`

For the following line I get 'undefined' when I select the line
`document.getElementById('form').submit();`

And the browser is refreshing all the time.

Could you please help me again?

**Comment by ArtemGovorov** [comment]
> +document.getElementById('form').submit();

You don't need a `+` sign before the statement, it was a part of the diff to illustrate that you need to add the `document.getElementById('form').submit();` line.

Nevertheless, the results described by you are correct and expected.

Selecting any expression in Quokka makes the tool to [evaluate it](https://quokkajs.com/docs/index.html#live-value-display) and display the result. The result returned by `document.getElementById('form').submit()` is `undefined`, `+undefined` in JavaScript is `NaN`, so `+document.getElementById('form').submit()` evaluates to `NaN`. The results are not specific to Quokka, you can `console.log(+document.getElementById('form').submit())` or `console.log(document.getElementById('form').submit())` and you'll get the same output.

> And the browser is refreshing all the time.

Have you removed the line `document.getElementById('form').submit();` before testing in browser? The line is only required to programmatically submit the form, you don't want to do it when visually testing your app.
