### ISSUE TITLE
Help with DOM manipulation & Quokka.js

### ISSUE THREAD

**Issue by kinglycodes** [wallabyjs/jsdom-quokka-plugin#17]
Hello Artem,

I have to ask again whether quokka.js can also be used if I am working on a website with DOM manipulation?

Here's my code:

```

// Programmatic Click Simulation (Tipp from Artem)
document.getElementById('button1').submit();

function loadCustomer(e) {
	const xhr = new XMLHttpRequest();

	xhr.open('GET', 'customer.json', true);

	xhr.onload = function () {
		if (this.status === 200) {
			console.log(this.responseText);
		}
	};

	xhr.send();
}



```

I followed your instruction from the last issue with the programmatic click simulation, but it doesn't work.

The return of quokka.js: 
document.getElementById('button1').submit();        **Cannot read property 'submit' of null**

What do I have to do to use quokka.js properly in VS Code without console logging in chrome all the time?

**Comment by ArtemGovorov** [comment]
The error means that the `button1` element is not found on the HTML page that you are loading to your Quokka file. By default, Quokka loads `index.html` file from the [same folder](https://github.com/wallabyjs/jsdom-quokka-plugin/blob/master/index.js#L16) with your running Quokka file (or from your project's root if you are running Quokka scratch file).

If your html file (with `button1`) is located elsewhere, you may specify the path to the file in your [Quokka configuration](https://github.com/wallabyjs/jsdom-quokka-plugin#example-2).
