### ISSUE TITLE
localStorage is not defined

### ISSUE THREAD

**Issue by jEnbuska** [wallabyjs/jsdom-quokka-plugin#3]
jsdom does not seem to implement localStorage. 
Is there any reason, why not to just add is as a plugin?
```
module.exports = {
    before: () => {
        const storage = {};
        if (!global.localStorage) {
            global.localStorage = {
                setItem(key, value){
                    storage[key] = value;
                },
                getItem(key){
                    return storage[key]
                },
                removeItem(key){
                    return delete storage[key]
                }
            }
        }
    }
};
```
 <--- seems to do the trick.

**Comment by ArtemGovorov** [comment]
Your solution looks good to me, perhaps [adding `sessionStorage` as well](https://github.com/tmpvar/jsdom/issues/1137#issuecomment-173039751) is a good idea. 

Would you be interested to send a pull request to this plugin (`jsdom-quokka-plugin`) with your solution?

**Comment by ArtemGovorov** [comment]
Thanks for sending the pull request!

**Comment by bhayward93** [comment]
Getting this issue again:

`​​​​Quokka 'Login.js' (node: v10.14.1, babel: v7.2.2, plugins: jsdom-quokka-plugin)​​​​
​​​​
​​sessionStorage is not available for opaque origins​​
  at ​​​Window.get sessionStorage [as sessionStorage]​​​ ​./node_modules/jsdom-quokka-plugin/node_modules/jsdom/lib/jsdom/browser/Window.js:264​`

**Comment by ArtemGovorov** [comment]
@bhayward93 Please update your `jsdom-quokka-plugin` to v1.0.14 and the issue should be resolved for you.
