### ISSUE TITLE
Quokka does not read JavaScript from external dependencies included in HTML head

### ISSUE THREAD

**Issue by seenakhoee** [wallabyjs/jsdom-quokka-plugin#7]
So I set up the global config correctly and it does grab the elements from the html page.
But I'm using the redux dependency and I get an error Redux is undefined when in the browser doing console.log the output of redux is given correctly.

![screen shot 2018-04-08 at 4 41 46 pm](https://user-images.githubusercontent.com/16523191/38473897-fcdbd572-3b4b-11e8-95e5-5c20d70364de.png)

**Comment by seenakhoee** [comment]
Funny enough doing CMD Shift P on mac then from there clicking Switch To Pro Edition solved the problem... I thought Pro edition becomes automative once the license is purchased. But looks like you need to start Quokka differently once purchased pro huh?

**Comment by ArtemGovorov** [comment]
When a [valid license is entered](https://quokkajs.com/docs/license.html), Quokka should automatically switch the Pro edition.
