### ISSUE TITLE
window.MutationObserver is not a constructor

### ISSUE THREAD

**Issue by ktiedt** [wallabyjs/jsdom-quokka-plugin#8]
It seems `MutationObserver` is not defined on the mock window object.

I have a PR to submit, but am not sure how to test it with the atom plugin...

**Comment by ArtemGovorov** [comment]
Unfortunately `MutationObserver` is not supported by [`jsdom`](https://github.com/jsdom/jsdom/issues/639), so the [PR fix](https://github.com/ktiedt/jsdom-quokka-plugin/commit/9d78ec3deb36adf2f1aa1c3156bd4d07016725dc) won't work. Until it is implemented in `jsdom`, you may use one of the shims/polyfills, [like this one](https://github.com/megawac/MutationObserver.js).

**Comment by ktiedt** [comment]
Can you elaborate on how to use this shim with quokka?

**Comment by ArtemGovorov** [comment]
@ktiedt Sure. According to [this post](https://github.com/jsdom/jsdom/issues/639#issuecomment-370612927), you may just `require`/`import` it right at the top of your (Quokka) file:

```js
require('mutationobserver-shim');
global.MutationObserver = window.MutationObserver;
```

or create [Quokka plugin](https://quokkajs.com/docs/extensibility.html) that would do the same.
